datadir: /opt/nuts/data
strictmode: false
http:
  default:
    address: :1323
    cors:
      origin: "*"
verbosity: debug
network:
  nodedid: did:nuts:3A7h6WS9xgrBzz9q4cw86DMFM2UhLuqoVLoxsH3A38j1
  enabletls: false
  disablenodeauthentication: true
  v2:
    gossipinterval: 500
